### ISSUE TITLE
how

### ISSUE THREAD

**Issue by majovec** [ProjectInfinity/PocketPanel#1]
how to install ?

**Comment by ProjectInfinity** [comment]
Hey, if you read the top of this repo you'll see that I mention it's not ready to be used.

I'm working on this in my spare time so I'm afraid I cannot have a estimate for you.

If you simply want to try it out in its kinda broken and completely unfinished state I'll write up a small Readme file description on how to do it. Keep in mind it currently will only run on windows because that's what I've been developing on.

**Comment by ProjectInfinity** [comment]
There is now a README file, but please read it carefully.

https://github.com/ProjectInfinity/PocketPanel/blob/master/README.md

**Comment by majovec** [comment]
:/ i have debian :/

**Comment by ProjectInfinity** [comment]
Like I said this is incredibly early in development. I will be working on making it run on Linux next, which shouldn't take a lot of time because there's not a lot platform specific code. I'll update this when it's pushed.

**Comment by ProjectInfinity** [comment]
Here you go.

https://github.com/ProjectInfinity/PocketPanel#ubuntu--debian

**Comment by ProjectInfinity** [comment]
Closing this ticket due to in-activity.
